### ISSUE TITLE
Update and Sort Items Causing an Error

### ISSUE THREAD

**Issue by aliyah-robinson** [pdatta1/csc256_lab_project#5]
<img width="1440" alt="Screenshot 2023-11-25 at 19 24 43" src="https://github.com/pdatta1/csc256_lab_project/assets/116529635/9d1d85f6-fa45-4c13-9c48-ff295bafe6fc">

Adding an item works, but when attempting to sort or update the added item an Error 500 comes up? Is this something on my end Patrick mentioned it may be a Chrome thing but just wanted to check!

**Comment by jordan-manus** [comment]
It seems that the 500 error is a chrome error. When testing, the same error showed, but wiping my cache corrected my problem.

**Comment by ekaulfuss** [comment]
For the update bug: a file was missing, I've added it, it should work now. 

For the sort bug: That's a separate issue, bug #6 covers this one.

I'm closing this bug since the update issue is corrected and the sort issue is a duplicate.
