### ISSUE TITLE
Still running into an error when attempting to update & sort

### ISSUE THREAD

**Issue by aliyah-robinson** [pdatta1/csc256_lab_project#8]
Below is an image that shows what happens on my end when I try to update an item

<img width="1440" alt="Screenshot 2023-11-28 at 12 24 24" src="https://github.com/pdatta1/csc256_lab_project/assets/116529635/5c96928e-270b-4bfa-9c56-5676077a0469">

When attempting to sort, nothing actually happens? The items remain in the same mismatched order that they were in? Any tips?

**Comment by jordan-manus** [comment]
This seems to be an issue with your server. The update_item template is present in the app. See the image below:

![image](https://github.com/pdatta1/csc256_lab_project/assets/94319835/6d6d2e26-1767-4744-a879-1db24b21deaa)



Try using a different browser, and making sure that you have the most up to date version of the app.

**Comment by aliyah-robinson** [comment]
I got this working too. Had to get the updated file!
