### ISSUE TITLE
The original template is gone

### ISSUE THREAD

**Issue by aliyah-robinson** [pdatta1/csc256_lab_project#9]
<img width="1440" alt="Template is gone" src="https://github.com/pdatta1/csc256_lab_project/assets/116529635/8a004428-0789-49f5-9d96-25910f3d4e55">

The new code kinda erased/altered the UI creation Jordan had did previously (unless you guys wanted it to look like this now?)

**Comment by jordan-manus** [comment]
It looks like you do not have the most up to date version of the app. I suggest you pull the latest version, which does have the updated UI features.

**Comment by ekaulfuss** [comment]
If you have confirmed you have the correct up to date code and this is still happening make sure that your IDE isn't trying to run the program in any sort of security mode.  I'm using Visual Studio Code and when you pull new code down it might go into a security mode and prevent dependencies and that sort of thing from getting pulled.  That's what happened to me, if it's that there should be a indication somewhere that you can click on to set to Trusted.

**Comment by aliyah-robinson** [comment]
I got it working! I must've had all the updated files, I'll report back if I come across any more issues. Thanks for the help!
